-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("BulkMailInbox", "enUS", true)


L["Alt - Delete Containing Mail"] = true
L["Alt-click Delete"] = true
L["Bulk Mail Inbox"] = true
L["Bulk Mail Inbox -- Inbox Items (%d mails, %d items, %s)"] = true
L["Bulk Mail Inbox Options"] = true
L["Cash"] = true
L["Clear Selected"] = true
L["Close"] = true
L["Ctrl - Return Containing Mail"] = true
L["Ctrl-click Return"] = true
L["Enable 'Take All' button in inbox."] = true
L["Enable Alt-Click on inbox items to delete the mail in which they are contained."] = true
L["Enable Ctrl-click on inbox items to return the mail in which they are contained."] = true
L["Enable Shift-click on inbox items to take them."] = true
L["Hint:"] = true
L["Inbox"] = true
L["Items (Inbox click actions apply)"] = true
L["Left click to open the config panel."] = true
L["Mail #"] = true
L["No"] = true
L["No items"] = true
L["Qty."] = true
L["Returnable"] = true
L["Right click to open the config menu."] = true
L["Sender"] = true
L["Shift - Take Item"] = true
L["Shift-click Take"] = true
L["Show Inbox GUI"] = true
L["Show the Inbox Items GUI"] = true
L["TTL"] = true
L["Take All"] = true
L["Take Cash"] = true
L["Take Selected"] = true
L["Yes"] = true
